import type { Metadata } from "next";
import "./globals.css";
import { ModalProvider } from "@/context/ModalContext";
import Modal from "@/components/Modal";
import Header from "@/components/Header";
import Filters from "@/components/Filters";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "project-management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-sans">
        <ModalProvider>
          <Header />
          <Modal>
            <Filters />
          </Modal>
          <div className="flex">
            <aside className="hidden md:block min-w-52 border-l border-gray-100">
              <Filters />
            </aside>
            <main>{children}</main>
          </div>
          <footer className="bg-red-500">فوتر</footer>
        </ModalProvider>
      </body>
    </html>
  );
}
